# Generated by Django 3.2 on 2023-11-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_wishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist_item',
            new_name='product',
        ),
    ]
