# Generated by Django 3.2 on 2023-11-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_alter_wishlist_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='artwork_id',
        ),
    ]
