# Generated by Django 3.2 on 2023-11-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_rename_product_wishlist_artwork_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='artwork_id',
            new_name='artwork',
        ),
    ]
