# Generated by Django 3.2 on 2023-11-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_alter_wishlist_artwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='artwork',
            new_name='product',
        ),
    ]
