# Generated by Django 3.2 on 2023-11-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactform',
            name='subject',
            field=models.CharField(blank=True, default='AEH Art Enquiry', max_length=150, null=True),
        ),
    ]
