# Generated by Django 3.2 on 2023-11-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_usercontactform_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontactform',
            name='user',
        ),
    ]
