# Generated by Django 3.2 on 2023-11-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('authors', models.CharField(max_length=500)),
                ('publication_year', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('volume_number', models.IntegerField(blank=True, null=True)),
                ('page_range', models.CharField(blank=True, default='n/a', max_length=500, null=True)),
                ('doi', models.CharField(blank=True, max_length=150, null=True)),
                ('link_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
