# Generated by Django 3.2 on 2023-11-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publications_volume_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publications',
            options={'ordering': ('-publication_year',), 'verbose_name': 'Publications', 'verbose_name_plural': 'Publications'},
        ),
    ]
