# Generated by Django 3.2 on 2023-11-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publications_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='link_url',
        ),
        migrations.AlterField(
            model_name='publications',
            name='doi',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
